class ArmConstants():


    STEPPER_INPUT = 0
    STEPPER_INIT_POS = 90

    LEFT_SHOULDER_INPUT = 1
    LEFT_SHOULDER_INIT_POS = 90

    RIGHT_SHOULDER_INPUT = 2
    RIGHT_SHOULDER_INIT_POS = 90

    ELBOW_INPUT = 3
    ELBOW_INIT_POS = 90

    WRIST_INPUT = 4
    WRIST_INIT_POS = 90

    END_EFFECTOR_INPUT = 5
    END_EFFECTOR_INIT_POS = 90